"""Fix datetimes by removing timezone

Revision ID: 0f7ac50dea73
Revises: c33a5cdc1685
Create Date: 2024-09-23 23:58:25.390006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7ac50dea73'
down_revision: Union[str, None] = 'c33a5cdc1685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
