"""add more web fields for posts

Revision ID: 2cdcb70350b9
Revises: 3eb0595003d4
Create Date: 2024-10-23 15:10:39.694327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cdcb70350b9'
down_revision: Union[str, None] = '3eb0595003d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('web_description', sa.String(length=300), nullable=True))
    op.add_column('posts', sa.Column('og_description', sa.String(length=300), nullable=True))
    op.add_column('posts', sa.Column('og_title', sa.String(length=150), nullable=True))
    op.add_column('posts', sa.Column('views_count', sa.Integer(), nullable=False, server_default="0"))
    op.alter_column('posts', 'short_description',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('posts', 'web_title',
               existing_type=sa.VARCHAR(length=150),
               nullable=True,
               existing_server_default=sa.text("'Chat-boty'::character varying"))
    op.alter_column('posts', 'keywords',
               existing_type=sa.VARCHAR(length=150),
               nullable=True,
               existing_server_default=sa.text("'Chat-boty'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'keywords',
               existing_type=sa.VARCHAR(length=150),
               nullable=False,
               existing_server_default=sa.text("'Chat-boty'::character varying"))
    op.alter_column('posts', 'web_title',
               existing_type=sa.VARCHAR(length=150),
               nullable=False,
               existing_server_default=sa.text("'Chat-boty'::character varying"))
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('posts', 'short_description',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.drop_column('posts', 'views_count')
    op.drop_column('posts', 'og_title')
    op.drop_column('posts', 'og_description')
    op.drop_column('posts', 'web_description')
    # ### end Alembic commands ###
