"""add web_title, keywords

Revision ID: 3eb0595003d4
Revises: 0f7ac50dea73
Create Date: 2024-10-23 14:59:33.781960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb0595003d4'
down_revision: Union[str, None] = '0f7ac50dea73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('web_title', sa.String(length=150), nullable=False, server_default='Chat-boty'))
    op.add_column('posts', sa.Column('keywords', sa.String(length=150), nullable=False, server_default='Chat-boty'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'keywords')
    op.drop_column('posts', 'web_title')
    # ### end Alembic commands ###
