"""empty message

Revision ID: 4a5dd8457615
Revises: f61fbb2d61b4
Create Date: 2024-09-12 23:54:50.695759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5dd8457615'
down_revision: Union[str, None] = 'f61fbb2d61b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('content', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'cases', ['id'])
    op.drop_column('cases', 'content_file')
    op.drop_column('cases', 'preview_file')
    op.add_column('posts', sa.Column('content', sa.Text(), nullable=True))
    op.drop_column('posts', 'content_file')
    op.drop_column('posts', 'preview_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('preview_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('content_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'content')
    op.add_column('cases', sa.Column('preview_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('content_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cases', type_='unique')
    op.drop_column('cases', 'content')
    # ### end Alembic commands ###
