"""Set file field nullable

Revision ID: 6ad1760ee48f
Revises: 9ec88dfca59f
Create Date: 2024-07-09 23:01:39.606820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad1760ee48f'
down_revision: Union[str, None] = '9ec88dfca59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'file',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'file',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
