"""extend keywords and slug length to 250

Revision ID: 81b276613d6f
Revises: d45a89c9081a
Create Date: 2025-12-14 19:58:08.624204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b276613d6f'
down_revision: Union[str, None] = 'd45a89c9081a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'slug',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=250),
               existing_nullable=False)
    op.alter_column('cases', 'keywords',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=250),
               existing_nullable=True)
    op.alter_column('posts', 'slug',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=250),
               existing_nullable=False,
               existing_server_default=sa.text('"substring"(md5((random())::text), 1, 8)'))
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('posts', 'keywords',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=250),
               existing_nullable=True,
               existing_server_default=sa.text("'Chat-boty'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'keywords',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True,
               existing_server_default=sa.text("'Chat-boty'::character varying"))
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('posts', 'slug',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False,
               existing_server_default=sa.text('"substring"(md5((random())::text), 1, 8)'))
    op.alter_column('cases', 'keywords',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('cases', 'slug',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###
