"""empty message

Revision ID: 9c51a9dc7085
Revises: 4a5dd8457615
Create Date: 2024-09-13 22:16:12.165530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c51a9dc7085'
down_revision: Union[str, None] = '4a5dd8457615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('preview_file_id', sa.String(length=100), nullable=False))
    op.add_column('cases', sa.Column('preview_og_file_id', sa.String(length=100), nullable=False))
    op.add_column('posts', sa.Column('preview_file_id', sa.String(length=100), nullable=True))
    op.add_column('posts', sa.Column('preview_og_file_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'preview_og_file_id')
    op.drop_column('posts', 'preview_file_id')
    op.drop_column('cases', 'preview_og_file_id')
    op.drop_column('cases', 'preview_file_id')
    # ### end Alembic commands ###
