"""Add new fields

Revision ID: 9ec88dfca59f
Revises: 17679a8495b2
Create Date: 2024-07-09 19:18:16.809663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec88dfca59f'
down_revision: Union[str, None] = '17679a8495b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=100), nullable=False, server_default='Untitled'))
    op.add_column('posts', sa.Column('short_description', sa.String(length=300), nullable=False, server_default=''))
    op.add_column('posts', sa.Column('reading_time', sa.Integer(), nullable=False, server_default='1'))
    op.create_unique_constraint(None, 'posts', ['id'])
    # ### end Alembic commands ###

    # Remove server default to ensure new records must specify values
    op.alter_column('posts', 'title', server_default=None)
    op.alter_column('posts', 'short_description', server_default=None)
    op.alter_column('posts', 'reading_time', server_default=None)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'reading_time')
    op.drop_column('posts', 'short_description')
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
