"""Add is published field in Cases and Models

Revision ID: c33a5cdc1685
Revises: a0c294de1097
Create Date: 2024-09-14 21:48:48.793041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c33a5cdc1685'
down_revision: Union[str, None] = 'a0c294de1097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('is_published', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('posts', sa.Column('is_published', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_published')
    op.drop_column('cases', 'is_published')
    # ### end Alembic commands ###
