"""add more web fields for cases

Revision ID: d45a89c9081a
Revises: 2cdcb70350b9
Create Date: 2024-10-23 21:26:45.800016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd45a89c9081a'
down_revision: Union[str, None] = '2cdcb70350b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('web_description', sa.String(length=300), nullable=True))
    op.add_column('cases', sa.Column('og_description', sa.String(length=300), nullable=True))
    op.add_column('cases', sa.Column('web_title', sa.String(length=150), nullable=True))
    op.add_column('cases', sa.Column('og_title', sa.String(length=150), nullable=True))
    op.add_column('cases', sa.Column('keywords', sa.String(length=150), nullable=True))
    op.add_column('cases', sa.Column('views_count', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'views_count')
    op.drop_column('cases', 'keywords')
    op.drop_column('cases', 'og_title')
    op.drop_column('cases', 'web_title')
    op.drop_column('cases', 'og_description')
    op.drop_column('cases', 'web_description')
    # ### end Alembic commands ###
