"""Add cases

Revision ID: f61fbb2d61b4
Revises: 60c057bbede6
Create Date: 2024-08-28 22:00:32.279406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61fbb2d61b4'
down_revision: Union[str, None] = '60c057bbede6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('short_description', sa.String(length=300), nullable=False),
    sa.Column('reading_time', sa.Integer(), nullable=False),
    sa.Column('content_file', sa.String(), nullable=True),
    sa.Column('preview_file', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_cases_slug'), 'cases', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_slug'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
